{"detail":"HTTPConnectionPool(host='stablediffusion', port=7860): Max retries exceeded with url: /api/generate-image (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x730524b254d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"}